version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - php
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web
  php:
    image: php:7-fpm
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: php
